'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import JSZip from 'jszip';
import {analyzeProject,applySafeFixes,Finding,ProjectFile,projectManifest} from '../lib/forensic';
import {verifyUiIntegrity} from '../lib/safety';

type Phase='idle'|'scan'|'fix'|'push'|'deploy'|'done';
const icon=(s:string)=>s==='critical'?'●':s==='high'?'◆':s==='medium'?'▲':'○';
const cleanPath=(p:string)=>p.replace(/^.*?(?=(src\/|app\/|pages\/|package\.json|next\.config|tsconfig|public\/))/,'');
export default function Home(){
 const [baseline,setBaseline]=useState<any>(null),[files,setFiles]=useState<ProjectFile[]>([]),[log,setLog]=useState(''),[findings,setFindings]=useState<Finding[]>([]),[phase,setPhase]=useState<Phase>('idle'),[elapsed,setElapsed]=useState(0),[ghToken,setGhToken]=useState(''),[vercelToken,setVercelToken]=useState(''),[owner,setOwner]=useState(''),[repo,setRepo]=useState(''),[branch,setBranch]=useState('main'),[projectId,setProjectId]=useState(''),[teamId,setTeamId]=useState(''),[repoId,setRepoId]=useState(''),[deployment,setDeployment]=useState<any>(null),[events,setEvents]=useState<string[]>([]),[autoFix,setAutoFix]=useState(true),[cycle,setCycle]=useState(0);
 const inputRef=useRef<HTMLInputElement>(null); const started=useRef(0);
 useEffect(()=>{if(!started.current||phase==='idle'||phase==='done')return;const t=setInterval(()=>setElapsed(Math.floor((Date.now()-started.current)/1000)),1000);return()=>clearInterval(t)},[phase]);
 const stats=useMemo(()=>({critical:findings.filter(x=>x.severity==='critical').length,high:findings.filter(x=>x.severity==='high').length,medium:findings.filter(x=>x.severity==='medium').length,files:files.length}),[findings,files]);
 function start(){if(!started.current)started.current=Date.now()}
 function addEvent(s:string){setEvents(e=>[`${new Date().toLocaleTimeString('vi-VN')}  ${s}`,...e].slice(0,40))}
 async function readInput(list:FileList|null){if(!list)return;const arr:ProjectFile[]=[];for(const f of Array.from(list)){if(f.name.toLowerCase().endsWith('.zip')){const z=await JSZip.loadAsync(f);for(const [p,v] of Object.entries(z.files)){if(v.dir||p.startsWith('__MACOSX/')||p.includes('node_modules/')||p.includes('.next/')||p.includes('.git/'))continue;try{const content=await (v as any).async('string');arr.push({path:cleanPath(p),content,size:content.length})}catch{}}}else{try{arr.push({path:cleanPath(f.webkitRelativePath||f.name),content:await f.text(),size:f.size})}catch{}}}setFiles(arr);setBaseline(projectManifest(arr));setFindings([]);setDeployment(null);start();addEvent(`Đã nạp ${arr.length} file • source tree đã được lọc`)}
 async function scan(customLog=log){start();setPhase('scan');setElapsed(0);addEvent('Forensic engine: quét manifest → paths → imports → env → log');await new Promise(r=>setTimeout(r,220));const f=analyzeProject(files,customLog);setFindings(f);addEvent(`Root-cause scan hoàn tất • ${f.length} finding • ${f.filter(x=>x.rootCause).length} root-cause`);setPhase('done')}
 async function fixAndPush(){start();setPhase('fix');addEvent('Patch gate: chỉ áp dụng deterministic safe fixes');const f=analyzeProject(files,log);const r=applySafeFixes(files,f,baseline||projectManifest(files));setFindings(f);if(r.applied.length&&verifyUiIntegrity(files,r.files).ok){setFiles(r.files);addEvent(`Đã áp dụng ${r.applied.length} safe fix • không đụng UI/component structure`);await push(r.files)}else{addEvent('Không có safe fix đủ bằng chứng — không push source chưa được sửa');setPhase('done')}}
 async function push(source=files){if(!ghToken||!owner||!repo){addEvent('Thiếu GitHub token / owner / repo');setPhase('done');return}setPhase('push');addEvent('Đang tạo atomic Git commit…');try{const payload={token:ghToken,owner,repo,branch,files:source.map(f=>({path:cleanPath(f.path),content:f.content})),message:`chore: forensic auto-fix${cycle?` cycle-${cycle}`:''}`};const r=await fetch('/api/github/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error);addEvent(`✓ GitHub ${d.commit?.slice(0,8)} • commit đã tạo`);await triggerDeploy(d.commit); }catch(e){addEvent('GitHub: '+(e instanceof Error?e.message:'lỗi'));setPhase('done')}}
 async function triggerDeploy(commit:string){if(!vercelToken||!projectId){addEvent('Thiếu Vercel token/projectId — GitHub push vẫn thành công');setPhase('done');return}setPhase('deploy');try{let rid=repoId;if(!rid){const q=new URLSearchParams({token:vercelToken,projectId});if(teamId)q.set('teamId',teamId);const pr=await fetch('/api/vercel/project?'+q);const pd=await pr.json();rid=pd.repoId||'';if(rid)setRepoId(String(rid))}if(rid){const r=await fetch('/api/vercel/deploy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:vercelToken,projectId,repoId:rid,ref:branch,teamId})});const d=await r.json();if(r.ok&&d.deployment){setDeployment(d.deployment);addEvent(`✓ Vercel deployment ${String(d.deployment.uid||'').slice(0,8)} được tạo trực tiếp`);await monitor(d.deployment.uid)}else{addEvent(`Vercel direct deploy: ${d.error||'không tạo được'} • chuyển sang monitor Git integration`);await monitor()}}else{addEvent('Không lấy được repoId từ Vercel project • monitor Git integration');await monitor()}}catch(e){addEvent('Vercel trigger: '+(e instanceof Error?e.message:'lỗi'));await monitor()}}
 function extractEventText(x:any):string{if(typeof x==='string')return x;return x?.text||x?.payload?.text||x?.payload?.message||x?.message||''}
 async function monitor(preId?:string){let id=preId||deployment?.uid||'';let last='';for(let i=0;i<90;i++){await new Promise(r=>setTimeout(r,2000));try{const sr=await fetch('/api/vercel/deployments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:vercelToken,projectId,teamId})});const sd=await sr.json();if(!sr.ok)throw Error(sd.error);const dep=id?(sd.deployments||[]).find((x:any)=>x.uid===id)||(sd.deployments||[])[0]:(sd.deployments||[])[0];if(dep){id=dep.uid;setDeployment(dep);if(dep.uid!==last){last=dep.uid;addEvent(`Deployment ${dep.uid.slice(0,8)} • ${dep.state||dep.readyState||'QUEUED'}`)}const er=await fetch('/api/vercel/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:vercelToken,id,teamId})});const ed=await er.json();const raw=Array.isArray(ed.events)?ed.events:[];const texts=raw.map(extractEventText).filter(Boolean);if(texts.length){const combined=texts.slice(-120).join('\n');if(combined!==log){setLog(combined);setFindings(analyzeProject(files,combined))}}const state=dep.state||dep.readyState;if(['READY','ERROR','CANCELED'].includes(state)){if(state==='READY'){addEvent('✓ READY • deployment đã vượt qua build');setPhase('done');return}addEvent(`✕ ${state} • lấy build events để forensic lại`);const newLog=texts.join('\n');const f=analyzeProject(files,newLog);setFindings(f);if(autoFix&&cycle<3){const r=applySafeFixes(files,f,baseline||projectManifest(files));if(r.applied.length&&verifyUiIntegrity(files,r.files).ok){setCycle(c=>c+1);setFiles(r.files);setLog(newLog);addEvent(`↻ AUTO-FIX LOOP ${cycle+1}/3 • có patch deterministic`);await push(r.files);return}addEvent('AUTO-FIX dừng: không có patch deterministic đủ bằng chứng')}setPhase('done');return}}}catch(e){addEvent('Monitor: '+(e instanceof Error?e.message:'lỗi'))}}setPhase('done');addEvent('Monitor hết thời gian 180s • deployment vẫn có thể đang chạy')}
 function severityClass(s:string){return `sev ${s}`}
 return <main><div className="noise"/><header className="top"><div className="brand"><span className="mark">F</span><div><b>FORENSIC</b><small>DEPLOY ENGINE // v3</small></div></div><div className="topstatus"><span className="pulse"/> deterministic • no AI required</div></header>
 <section className="hero"><div className="eyebrow">VERCEL // AUTOPSY // AUTO-FIX LOOP</div><h1>Deployment lỗi? <em>Đừng đoán.</em> Hãy điều tra.</h1><p>Nạp ZIP/thư mục + log. Engine dựng hồ sơ lỗi, truy root-cause, chỉ sửa những gì có bằng chứng, commit lên GitHub và theo dõi Vercel realtime. Giao diện/source project được giữ nguyên.</p><div className="actions"><button className="primary" onClick={()=>inputRef.current?.click()}>＋ Nạp ZIP / thư mục</button><button onClick={()=>scan()} disabled={!files.length}>Chạy forensic scan</button><label className="badge" style={{display:'flex',alignItems:'center',gap:7}}><input type="checkbox" checked={autoFix} onChange={e=>setAutoFix(e.target.checked)}/> Auto-fix an toàn</label><input ref={inputRef} hidden type="file" multiple {...({webkitdirectory:true,directory:true} as any)} accept=".zip,.js,.jsx,.ts,.tsx,.json,.mjs,.cjs,.css,.scss,.md,.env" onChange={e=>readInput(e.target.files)}/></div></section>
 <section className="grid"><div className="panel logpanel"><div className="panelhead"><div><span className="kicker">01 / INPUT</span><h2>Build log</h2></div><span className="badge">{files.length} files</span></div><textarea value={log} onChange={e=>setLog(e.target.value)} placeholder="Dán toàn bộ log Vercel vào đây…\n\nEngine sẽ ưu tiên lỗi gốc trước lỗi dây chuyền."/><div className="drop" onClick={()=>inputRef.current?.click()}><strong>ZIP hoặc folder</strong><span>Kéo thả project vào đây • tự loại node_modules/.next/.git</span></div></div>
 <div className="panel setup"><div className="panelhead"><div><span className="kicker">02 / DELIVERY</span><h2>GitHub → Vercel</h2></div><span className="badge green">TOKEN ONLY</span></div><div className="fields"><input placeholder="GitHub token" type="password" value={ghToken} onChange={e=>setGhToken(e.target.value)}/><div className="row"><input placeholder="owner" value={owner} onChange={e=>setOwner(e.target.value)}/><input placeholder="repo" value={repo} onChange={e=>setRepo(e.target.value)}/></div><input placeholder="branch • main" value={branch} onChange={e=>setBranch(e.target.value)}/><input placeholder="Vercel token" type="password" value={vercelToken} onChange={e=>setVercelToken(e.target.value)}/><input placeholder="Vercel projectId" value={projectId} onChange={e=>setProjectId(e.target.value)}/><div className="row"><input placeholder="repoId (tự lấy nếu Vercel link GitHub)" value={repoId} onChange={e=>setRepoId(e.target.value)}/><input placeholder="teamId (nếu có)" value={teamId} onChange={e=>setTeamId(e.target.value)}/></div></div><button className="deploy" disabled={!files.length||phase==='push'||phase==='deploy'||phase==='fix'} onClick={()=>autoFix?fixAndPush():push()}>Sửa an toàn → GitHub → Vercel ↗</button><p className="security">Token chỉ đi qua server route tới GitHub/Vercel; không lưu database. Auto-fix chỉ chạy khi có patch deterministic.</p></div></section>
 <section className="dashboard"><div className="stat"><span>FILES</span><b>{stats.files}</b></div><div className="stat"><span>CRITICAL</span><b>{stats.critical}</b></div><div className="stat"><span>HIGH</span><b>{stats.high}</b></div><div className="stat"><span>ELAPSED</span><b>{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</b></div><div className="stat"><span>CYCLE</span><b>{cycle}/3</b></div><div className="phase"><span className={`phase-dot ${phase}`}/><b>{phase==='scan'?'FORENSIC SCANNING':phase==='fix'?'SAFE AUTO-FIX':phase==='push'?'PUSHING GITHUB':phase==='deploy'?'LIVE VERCEL MONITOR':'SYSTEM READY'}</b></div></section>
 <section className="results"><div className="panel findings"><div className="panelhead"><div><span className="kicker">03 / AUTOPSY</span><h2>Root-cause findings</h2></div><span className="count">{findings.length} findings</span></div>{findings.length===0?<div className="empty"><div className="radar">◎</div><h3>Chưa có kết quả</h3><p>Nạp project + log, sau đó chạy forensic scan.</p></div>:<div className="findinglist">{findings.map((f,i)=><article key={f.id+i} className="finding"><div className={severityClass(f.severity)}>{icon(f.severity)}</div><div className="findingbody"><div className="findingtop"><h3>{f.title}</h3><span>{f.file||'PROJECT'}{f.line?`:${f.line}`:''} • {f.confidence}%</span></div><p>{f.message}</p><div className="fix"><b>{f.rootCause?'ROOT CAUSE':'FIX'}</b>{f.fix}</div></div></article>)}</div>}</div>
 <aside className="panel monitor"><div className="panelhead"><div><span className="kicker">04 / REAL-TIME</span><h2>Deployment monitor</h2></div>{deployment&&<span className={`state ${String(deployment.state||deployment.readyState||'').toLowerCase()}`}>{deployment.state||deployment.readyState}</span>}</div><div className="timeline">{['SCAN PROJECT','ROOT CAUSE','GITHUB COMMIT','VERCEL BUILD','READY'].map((x,i)=><div className="tl" key={x}><span className={i<(phase==='done'?5:phase==='deploy'?4:phase==='push'?3:phase==='fix'?2:phase==='scan'?2:0)?'on':''}/><div><b>{x}</b><small>{i===0?'manifest / imports / env':i===1?'evidence + confidence':i===2?'atomic Git tree commit':i===3?'poll status + build events':i===4?'production verification':' '}</small></div></div>)}</div><div className="events">{events.length?events.map((x,i)=><div key={i}>{x}</div>):<div className="muted">Chưa có hoạt động.</div>}</div></aside></section>
 <footer>FORENSIC ENGINE v3 <span>•</span> Không AI API bắt buộc <span>•</span> Safe deterministic fixes <span>•</span> Evidence-first</footer></main>}
