"use client";
import {useEffect,useRef,useState} from "react";
import {ArrowUp,Archive,BrainCircuit,ChevronDown,Code2,FileArchive,Folder,History,LayoutDashboard,Menu,Paperclip,Plus,Search,Settings,Sparkles,Upload,X,Zap,Command,PanelRight,ShieldCheck,Boxes,Workflow,Globe2,Database,Network,SlidersHorizontal} from "lucide-react";
import JSZip from "jszip";
type KnowledgeResult={id:string;title:string;domain?:string}; type Msg={id:string;role:"user"|"assistant";text:string;results?:KnowledgeResult[]}; type Chat={id:string;title:string;messages:Msg[]};
const KEY="hpgk.v2.1.chats"; const MEM="hpgk.v2.1.memory";
const uid=()=>{try{return crypto.randomUUID()}catch{return `${Date.now()}-${Math.random().toString(36).slice(2)}`}};
const safeStats={entries:0,domains:0,relationships:0};
const safeText=(v:unknown,fallback="")=>typeof v==="string"?v:fallback;
const normalizeChats=(value:unknown):Chat[]=>{
 if(!Array.isArray(value)) return initial;
 const out=value.map((c:any)=>({
   id:safeText(c?.id,uid()),
   title:safeText(c?.title,"Cuộc trò chuyện"),
   messages:Array.isArray(c?.messages)?c.messages.filter((m:any)=>m&&typeof m==="object"&&typeof m.id==="string"&&(m.role==="user"||m.role==="assistant")&&typeof m.text==="string").map((m:any)=>({id:m.id,role:m.role,text:m.text,results:Array.isArray(m.results)?m.results.filter((r:any)=>r&&typeof r.id==="string"&&typeof r.title==="string").map((r:any)=>({id:r.id,title:r.title,domain:typeof r.domain==="string"?r.domain:undefined})):undefined})):[]
 }));
 return out.length?out:initial;
};
const storageGet=(key:string)=>{try{return typeof window!=="undefined"?window.localStorage.getItem(key):null}catch{return null}};
const storageSet=(key:string,value:string)=>{try{if(typeof window!=="undefined")window.localStorage.setItem(key,value)}catch{}};
const initial:Chat[]=[{id:"welcome",title:"Chào mừng đến HPGK",messages:[{id:"1",role:"assistant",text:"Chào bạn 👋\n\nHPGK v1.4 là không gian trí tuệ ưu tiên tiếng Việt. Tôi có thể tra cứu knowledge nội bộ, ghi nhớ ngữ cảnh trong trình duyệt và tiếp nhận source/ZIP để phân tích."}]}];
const suggestions=[["Xây website","Thiết kế một website premium, responsive, accessible và có kiến trúc production-ready."],["Phân tích source","Phân tích project, kiến trúc, dependency, bảo mật, hiệu năng và điểm cần nâng cấp."],["Xây AI Agent","Thiết kế agent có context, memory, tools, retrieval, kiểm chứng và giới hạn an toàn."],["Tối ưu hệ thống","Tìm bottleneck và lập kế hoạch tối ưu theo bằng chứng thay vì đoán mò."]];
export default function HPGK(){
 const [boot,setBoot]=useState(true),[side,setSide]=useState(true),[right,setRight]=useState(true),[q,setQ]=useState(""),[search,setSearch]=useState(""),[files,setFiles]=useState<string[]>([]),[active,setActive]=useState("welcome"),[chats,setChats]=useState<Chat[]>(initial),[memory,setMemory]=useState<string[]>([]),[stats,setStats]=useState(safeStats),[busy,setBusy]=useState(false); const ref=useRef<HTMLInputElement>(null); const chat=chats.find(x=>x.id===active) || chats[0] || initial[0]; const chatMessages=Array.isArray(chat?.messages)?chat.messages:[]; 
 useEffect(()=>{
 const c=storageGet(KEY); if(c){try{setChats(normalizeChats(JSON.parse(c)))}catch{setChats(initial)}}
 const m=storageGet(MEM); if(m){try{const parsed=JSON.parse(m);if(Array.isArray(parsed))setMemory(parsed.filter((x):x is string=>typeof x==="string").slice(0,30))}catch{setMemory([])}}
 fetch('/api/knowledge',{cache:'no-store'}).then(r=>r.ok?r.json():null).then(x=>{if(x?.stats)setStats({entries:Number(x.stats.entries)||0,domains:Number(x.stats.domains)||0,relationships:Number(x.stats.relationships)||0})}).catch(()=>{});
},[]);
 useEffect(()=>{storageSet(KEY,JSON.stringify(chats));},[chats]);
 useEffect(()=>{storageSet(MEM,JSON.stringify(memory));},[memory]);
 const send=async(value=q)=>{value=value.trim();if(!value)return;setBusy(true);const u={id:uid(),role:"user" as const,text:value};let results:any[]=[];try{const r=await fetch('/api/knowledge?q='+encodeURIComponent(value));const j=await r.json();results=j.results||[];}catch{} const names=results.slice(0,5).map(x=>`• ${x.title} — ${x.domain}`).join("\n");const a={id:uid(),role:"assistant" as const,text:`Tôi đã phân tích yêu cầu theo pipeline HPGK.\n\n1. Hiểu ý định\n2. Tra cứu ${results.length} mục knowledge phù hợp\n3. Xây context\n4. Đề xuất hướng thực thi\n5. Kiểm chứng đầu ra\n\nKnowledge nổi bật:\n${names||"• Chưa có mục khớp trực tiếp — cần mở rộng knowledge/project context."}\n\nĐể thực thi code hoặc thay đổi project thật, HPGK cần được cấp project/tool tương ứng.`,results}; setChats(cs=>cs.map(c=>c.id===active?{...c,messages:[...c.messages,u,a],title:c.title==="Chào mừng đến HPGK"?value.slice(0,34):c.title}:c));setMemory(m=>[value,...m].slice(0,30));setQ("");setBusy(false);};
 const newChat=()=>{const id=uid();setChats(c=>[{id,title:"Cuộc trò chuyện mới",messages:[]},...c]);setActive(id)};
 const upload=async(l:FileList|null)=>{if(!l)return;for(const f of Array.from(l)){setFiles(x=>[...x,f.name]);if(f.name.toLowerCase().endsWith('.zip')){try{const z=await JSZip.loadAsync(f);const names=Object.keys(z.files).slice(0,500);setMemory(m=>([`ZIP ${f.name}: ${names.length} mục`,...m]).slice(0,30));}catch{}}}};
 if(boot)return <div className="boot" onClick={()=>setBoot(false)}><div className="boot-orb"><span/><span/><span/></div><div className="boot-brand"><b>HPGK</b><small>INTELLIGENCE WORKSPACE</small></div><p>HIỂU · GHI NHỚ · TRA CỨU · XÂY DỰNG · KIỂM CHỨNG</p><button>VÀO KHÔNG GIAN LÀM VIỆC <ArrowUp/></button></div>;
 return <main className="app"><div className="ambient a1"/><div className="ambient a2"/><div className="gridfx"/><header className="topbar"><button className="iconbtn" onClick={()=>setSide(!side)}><Menu/></button><div className="brand"><strong>HPGK</strong><span>AI WORKSPACE</span></div><div className="status"><i/> HỆ THỐNG ĐANG HOẠT ĐỘNG</div><div className="top-actions"><button className="iconbtn"><Command/></button><button className="iconbtn"><SlidersHorizontal/></button><button className="iconbtn" onClick={()=>setRight(!right)}><PanelRight/></button></div></header><div className="layout">
 {side&&<aside className="sidebar"><button className="newchat" onClick={newChat}><Plus/> Cuộc trò chuyện mới <kbd>⌘K</kbd></button><label className="searchbox"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm cuộc trò chuyện"/></label><div className="sect">KHÔNG GIAN</div>{[["Tổng quan",LayoutDashboard],["Dự án",Folder],["Kho kiến thức",BrainCircuit],["Quy trình Agent",Workflow],["Tệp & Artifacts",Archive]].map(([t,I]:any)=><button className="nav" key={t}><I/>{t}</button>)}<div className="sect">GẦN ĐÂY</div>{chats.filter(c=>safeText(c.title,"Cuộc trò chuyện").toLowerCase().includes(search.toLowerCase())).map(c=><button className={"history "+(c.id===active?"active":"")} key={c.id} onClick={()=>setActive(c.id)}><History/>{c.title}</button>)}<div className="side-bottom"><button className="nav"><Settings/>Cài đặt</button><div className="profile"><span>GK</span><div><b>HPGK Workspace</b><small>Trí tuệ nội bộ</small></div><ChevronDown/></div></div></aside>}
 <section className="center">{chatMessages.length<=1?<div className="welcome"><div className="eyebrow"><Sparkles/> TRUNG TÂM TRÍ TUỆ HPGK</div><h1>Xin chào.<br/><em>Bạn muốn xây gì?</em></h1><p className="sub">Một không gian duy nhất để suy nghĩ, lập trình, phân tích project, làm việc với file và khai thác knowledge — ưu tiên tiếng Việt.</p><div className="suggestions">{suggestions.map(([a,b])=><button key={a} onClick={()=>send(b)}><div><b>{a}</b><span>{b}</span></div><ArrowUp/></button>)}</div><div className="capabilities"><span><BrainCircuit/> Knowledge {stats.entries.toLocaleString()}</span><span><Code2/> Code</span><span><FileArchive/> ZIP / File</span><span><ShieldCheck/> Kiểm chứng</span></div></div>:<div className="conversation"><div className="conversation-title"><small>CUỘC TRÒ CHUYỆN</small><h2>{chat.title}</h2></div>{chatMessages.map(m=><article className={"message "+m.role} key={m.id}><div className="avatar">{m.role==="assistant"?<Sparkles/>:"G"}</div><div className="message-body"><small>{m.role==="assistant"?"HPGK":"BẠN"}</small><p>{m.text}</p>{(m.results ?? []).length > 0 && <div className="result-chips">{(m.results ?? []).slice(0,6).map((r: KnowledgeResult)=><span key={r.id}><Database/> {r.title}</span>)}</div>}</div></article>)}</div>}
 <div className="composer-zone">{files.length>0&&<div className="attachments">{files.map((f,i)=><span key={i}><FileArchive/>{f}<X onClick={()=>setFiles(x=>x.filter((_,j)=>j!==i))}/></span>)}</div>}<div className="composer"><label title="Đính kèm file"><Paperclip/><input ref={ref} type="file" multiple onChange={e=>upload(e.target.files)} accept=".zip,.pdf,.txt,.md,.json,.js,.ts,.tsx,.jsx,.html,.css,.png,.jpg,.jpeg"/></label><textarea rows={1} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder={busy?"HPGK đang phân tích…":"Hỏi HPGK bất cứ điều gì…"}/><button disabled={busy} onClick={()=>send()}><ArrowUp/></button></div><div className="composer-meta"><span><Zap/> {busy?"Đang suy luận và tra cứu":"Sẵn sàng hiểu ngữ cảnh"}</span><span>Enter để gửi · Shift + Enter xuống dòng</span></div></div></section>
 {right&&<aside className="inspector"><div className="inspector-head"><div><small>TRUNG TÂM NGỮ CẢNH</small><b>Thông tin phiên</b></div><button className="iconbtn" onClick={()=>setRight(false)}><X/></button></div><div className="system-card"><div className="system-icon"><Sparkles/></div><div><b>HPGK đã sẵn sàng</b><span>Knowledge cục bộ · không cần API AI để tra cứu</span></div></div><div className="panel-section"><small>THỐNG KÊ KNOWLEDGE</small><div className="context-row"><Boxes/><span>Mục kiến thức</span><b>{stats.entries.toLocaleString()}</b></div><div className="context-row"><Network/><span>Quan hệ</span><b>{stats.relationships.toLocaleString()}</b></div><div className="context-row"><Globe2/><span>Lĩnh vực</span><b>{stats.domains}</b></div></div><div className="panel-section"><small>NGỮ CẢNH ĐANG DÙNG</small>{[["Tệp đã tải",String(files.length),FileArchive],["Memory",String(memory.length)+" mục",BrainCircuit],["Knowledge","Đang hoạt động",Boxes]].map(([a,b,I]:any)=><div className="context-row" key={a}><I/><span>{a}</span><b>{b}</b></div>)}</div><div className="panel-section"><small>QUY TRÌNH TRÍ TUỆ</small>{["Hiểu ý định","Tra cứu knowledge","Lập context","Lập kế hoạch","Kiểm tra kết quả","Tự đánh giá"].map((x,i)=><div className="pipeline" key={x}><i>{i+1}</i><span>{x}</span><b>✓</b></div>)}</div><div className="upload-card" onClick={()=>ref.current?.click()}><Upload/><b>Kéo thả project / ZIP</b><span>Code · tài liệu · hình ảnh</span></div><div className="inspector-footer"><Globe2/> Ưu tiên tiếng Việt · Memory cục bộ</div></aside>}
 </div></main>;
}
